name: Run MATLAB Tests on GitHub-Hosted Runner
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest] #, macos-latest]
        release: [R2020b,latest]
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with: 
            release: ${{matrix.release}}
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v2
        with: 
            select-by-folder: test
            select-by-tag: Github
            code-coverage-cobertura: coverage.xml

  badge:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: action-badges/create-orphan-branch@0.1.1
        with:
          branch-name: badges

      - name: Make Coverage Badge
        uses: action-badges/cobertura-coverage-xml-badges@0.3.0
        with:
          file-name: coverage.svg
          badge-branch: badges
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          coverage-file-name: coverage.xml

