name: Run MATLAB Tests on GitHub-Hosted Runner
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest] #, macos-latest]
        release: [R2020b,latest]
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with: 
            release: ${{matrix.release}}
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v2
        with: 
            select-by-folder: test
            select-by-tag: Github
            use-parallel: false
            code-coverage-cobertura: ./coverage.xml


