name: Run MATLAB Tests on GitHub-Hosted Runner
on: [pull_request]
jobs:
  test:
    name: Run MATLAB Tests and Generate Artifacts
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest] #, macos-latest]
        release: [R2021a, latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with: 
            release: ${{matrix.release}}
            products: Signal_Processing_Toolbox Parallel_Computing_Toolbox Image_Processing_Toolbox Statistics_and_Machine_Learning_Toolbox
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v2
        with: 
            select-by-folder: test
            select-by-tag: Github
            code-coverage-cobertura: coverage.xml
      - name: Make Coverage Badge
        uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: a38004ac36b1dbdb87cb61852435ab3d
          token: ${{ secrets.GIST_TOKEN }}

